// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ATable: typeof import('ant-design-vue/es')['Table']
    Day: typeof import('./src/components/Day.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Line: typeof import('./src/components/Line.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
